indicators_list = [
    # Overlays
    {"name": "avgprice", "inputs": ["High", "Low", "Close"], "params": {}, "param_grid": {}},
    {
        "name": "bbands",
        "inputs": ["Close"],
        "params": {"period": 20, "stddev": 2},
        "param_grid": {"period": [10, 20, 30], "stddev": [1.5, 2, 2.5]}
    },
    {"name": "dema", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": [10, 20, 30, 50]}},
    {"name": "ema", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": [10, 20, 30, 50]}},
    {"name": "hma", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": [10, 20, 30, 50]}},
    {"name": "kama", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": [10, 20, 30, 50]}},
    {"name": "linreg", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": [10, 20, 30, 50]}},
    {"name": "medprice", "inputs": ["High", "Low"], "params": {}, "param_grid": {}},
    {"name": "psar", "inputs": ["High", "Low"], "params": {"start": 0.02, "increment": 0.02, "max": 0.2}, "param_grid": {"start": [0.01, 0.02, 0.03], "increment": [0.01, 0.02, 0.03], "max": [0.1, 0.2, 0.3]}},
    {"name": "sma", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": [10, 20, 30, 50]}},
    {"name": "tema", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": [10, 20, 30, 50]}},
    {"name": "trima", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": [10, 20, 30, 50]}},
    {"name": "tsf", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": [10, 20, 30, 50]}},
    {"name": "typprice", "inputs": ["High", "Low", "Close"], "params": {}, "param_grid": {}},
    {"name": "vidya", "inputs": ["Close"], "params": {"period": 20, "alpha": 0.2}, "param_grid": {"period": [10, 20, 30, 50], "alpha": [0.1, 0.2, 0.3]}},
    {"name": "vwma", "inputs": ["Close", "volume"], "params": {"period": 20}, "param_grid": {"period": [10, 20, 30, 50]}},
    {"name": "wcprice", "inputs": ["High", "Low", "Close"], "params": {}, "param_grid": {}},
    {"name": "wilders", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": [10, 20, 30, 50]}},
    {"name": "wma", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": [10, 20, 30, 50]}},
    {"name": "zlema", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": [10, 20, 30, 50]}},

    # Indicators
    {"name": "ad", "inputs": ["High", "Low", "Close", "volume"], "params": {}, "param_grid": {}},
    {"name": "adosc", "inputs": ["High", "Low", "Close", "volume"], "params": {"fast_period": 3, "sLow_period": 10}, "param_grid": {"fast_period": [3, 5, 7], "sLow_period": [10, 14, 20]}},
    {"name": "adx", "inputs": ["High", "Low", "Close"], "params": {"period": 14}, "param_grid": {"period": [10, 14, 20, 30]}},
    {"name": "adxr", "inputs": ["High", "Low", "Close"], "params": {"period": 14}, "param_grid": {"period": [10, 14, 20, 30]}},
    {"name": "ao", "inputs": ["High", "Low"], "params": {}, "param_grid": {}},
    {"name": "apo", "inputs": ["Close"], "params": {"fast_period": 12, "sLow_period": 26}, "param_grid": {"fast_period": [10, 12, 14], "sLow_period": [24, 26, 30]}},
    {"name": "aroon", "inputs": ["High", "Low"], "params": {"period": 14}, "param_grid": {"period": [10, 14, 20, 25]}},
    {"name": "aroonosc", "inputs": ["High", "Low"], "params": {"period": 14}, "param_grid": {"period": [10, 14, 20, 25]}},
    {"name": "atr", "inputs": ["High", "Low", "Close"], "params": {"period": 14}, "param_grid": {"period": [10, 14, 20, 30]}},
    {"name": "bop", "inputs": ["Open", "High", "Low", "Close"], "params": {}, "param_grid": {}},
    {"name": "cci", "inputs": ["High", "Low", "Close"], "params": {"period": 20}, "param_grid": {"period": [14, 20, 30, 50]}},
    {"name": "cmo", "inputs": ["Close"], "params": {"period": 14}, "param_grid": {"period": [10, 14, 20, 30]}},
    {"name": "cvi", "inputs": ["Close"], "params": {"period": 14}, "param_grid": {"period": [10, 14, 20, 30]}},
    {"name": "di", "inputs": ["High", "Low", "Close"], "params": {"period": 14}, "param_grid": {"period": [10, 14, 20, 30]}},
    {"name": "dm", "inputs": ["High", "Low"], "params": {"period": 14}, "param_grid": {"period": [10, 14, 20, 30]}},
    {"name": "dpo", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": [14, 20, 30, 50]}},
    {"name": "dx", "inputs": ["High", "Low", "Close"], "params": {"period": 14}, "param_grid": {"period": [10, 14, 20, 30]}},
    {"name": "emv", "inputs": ["High", "Low", "volume"], "params": {"period": 14}, "param_grid": {"period": [10, 14, 20, 30]}},
    {"name": "fisher", "inputs": ["Close"], "params": {"period": 10}, "param_grid": {"period": [5, 10, 14, 20]}},
    {"name": "fosc", "inputs": ["Close"], "params": {"period": 10}, "param_grid": {"period": [5, 10, 14, 20]}},
    {"name": "kvo", "inputs": ["High", "Low", "Close", "volume"], "params": {"fast_period": 34, "sLow_period": 55}, "param_grid": {"fast_period": [30, 34, 40], "sLow_period": [50, 55, 60]}},
    {"name": "linregintercept", "inputs": ["Close"], "params": {"period": 14}, "param_grid": {"period": [10, 14, 20, 30]}},
    {"name": "linregslope", "inputs": ["Close"], "params": {"period": 14}, "param_grid": {"period": [10, 14, 20, 30]}},
    {
        "name": "macd",
        "inputs": ["Close"],
        "params": {"short_period": 12, "long_period": 26, "signal_period": 9},
        "param_grid": {"short_period": [10, 12, 14], "long_period": [24, 26, 30], "signal_period": [7, 9, 12]}
    },
    {"name": "marketfi", "inputs": ["High", "Low", "volume"], "params": {}, "param_grid": {}},
    {"name": "mass", "inputs": ["High", "Low"], "params": {"period": 9}, "param_grid": {"period": [7, 9, 12, 15]}},
    {"name": "mfi", "inputs": ["High", "Low", "Close", "volume"], "params": {"period": 14}, "param_grid": {"period": [10, 14, 20, 30]}},
    {"name": "mom", "inputs": ["Close"], "params": {"period": 10}, "param_grid": {"period": [5, 10, 14, 20]}},
    {"name": "msw", "inputs": ["Close"], "params": {"period": 14}, "param_grid": {"period": [10, 14, 20, 30]}},
    {"name": "natr", "inputs": ["High", "Low", "Close"], "params": {"period": 14}, "param_grid": {"period": [10, 14, 20, 30]}},
    {"name": "nvi", "inputs": ["Close", "volume"], "params": {}, "param_grid": {}},
    {"name": "obv", "inputs": ["Close", "volume"], "params": {}, "param_grid": {}},
    {"name": "ppo", "inputs": ["Close"], "params": {"fast_period": 12, "sLow_period": 26}, "param_grid": {"fast_period": [10, 12, 14], "sLow_period": [24, 26, 30]}},
    {"name": "pvi", "inputs": ["Close", "volume"], "params": {}, "param_grid": {}},
    {"name": "qstick", "inputs": ["Open", "Close"], "params": {"period": 10}, "param_grid": {"period": [5, 10, 14, 20]}},
    {"name": "roc", "inputs": ["Close"], "params": {"period": 12}, "param_grid": {"period": [10, 12, 20, 30]}},
    {"name": "rocr", "inputs": ["Close"], "params": {"period": 12}, "param_grid": {"period": [10, 12, 20, 30]}},
    {"name": "rsi", "inputs": ["Close"], "params": {"period": 14}, "param_grid": {"period": [10, 14, 20, 30]}},
    {"name": "stoch", "inputs": ["High", "Low", "Close"], "params": {"k_period": 14, "d_period": 3, "smooth_period": 3}, "param_grid": {"k_period": [10, 14, 20], "d_period": [3, 5, 7], "smooth_period": [3, 5, 7]}},
    {"name": "stochrsi", "inputs": ["Close"], "params": {"period": 14, "k_period": 14, "d_period": 3}, "param_grid": {"period": [10, 14, 20], "k_period": [10, 14, 20], "d_period": [3, 5, 7]}},
    {"name": "tr", "inputs": ["High", "Low", "Close"], "params": {}, "param_grid": {}},
    {"name": "trix", "inputs": ["Close"], "params": {"period": 15}, "param_grid": {"period": [10, 15, 20, 30]}},
    {"name": "ultosc", "inputs": ["High", "Low", "Close"], "params": {"period1": 7, "period2": 14, "period3": 28}, "param_grid": {"period1": [5, 7, 10], "period2": [12, 14, 16], "period3": [25, 28, 30]}},
    {"name": "vhf", "inputs": ["High", "Low"], "params": {"period": 28}, "param_grid": {"period": [20, 28, 35, 50]}},
    {"name": "volatility", "inputs": ["Close"], "params": {"period": 10}, "param_grid": {"period": [5, 10, 14, 20]}},
    {"name": "vosc", "inputs": ["volume"], "params": {"fast_period": 3, "sLow_period": 10}, "param_grid": {"fast_period": [3, 5, 7], "sLow_period": [10, 14, 20]}},
    {"name": "wad", "inputs": ["High", "Low", "Close", "volume"], "params": {}, "param_grid": {}},
    {"name": "willr", "inputs": ["High", "Low", "Close"], "params": {"period": 14}, "param_grid": {"period": [10, 14, 20, 30]}},

    # Maths
    {"name": "stddev", "inputs": ["Close"], "params": {"period": 14}, "param_grid": {"period": [10, 14, 20, 30]}},
    {"name": "max", "inputs": ["Close"], "params": {"period": 14}, "param_grid": {"period": [10, 14, 20, 30]}},
    {"name": "min", "inputs": ["Close"], "params": {"period": 14}, "param_grid": {"period": [10, 14, 20, 30]}},
    {"name": "sum", "inputs": ["Close"], "params": {"period": 14}, "param_grid": {"period": [10, 14, 20, 30]}},
    {"name": "var", "inputs": ["Close"], "params": {"period": 14}, "param_grid": {"period": [10, 14, 20, 30]}},
    {"name": "abs", "inputs": ["Close"], "params": {}, "param_grid": {}},
    {"name": "ln", "inputs": ["Close"], "params": {}, "param_grid": {}},
    {"name": "sqrt", "inputs": ["Close"], "params": {}, "param_grid": {}},
]