indicators_list = [
    # Overlays
    {"name": "avgprice", "inputs": ["Open", "High", "Low", "Close"], "params": {}, "param_grid": {}},
    {
        "name": "bbands",
        "inputs": ["Close"],
        "params": {"period": 20, "stddev": 2},
        "param_grid": {"period": (10, 30), "stddev": (1.5, 2.5)}
    },
    {"name": "dema", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": (10, 50)}},
    {"name": "ema", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": (10, 50)}},
    {"name": "hma", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": (10, 50)}},
    {"name": "kama", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": (10, 50)}},
    {"name": "linreg", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": (10, 50)}},
    {"name": "medprice", "inputs": ["High", "Low"], "params": {}, "param_grid": {}},
    {
        "name": "psar",
        "inputs": ["High", "Low"],
        "params": {"acceleration_factor_step": 0.02, "acceleration_factor_maximum": 0.2},
        "param_grid": {"acceleration_factor_step": (0.01, 0.03), "acceleration_factor_maximum": (0.1, 0.3)}
    },
    {"name": "sma", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": (10, 50)}},
    {"name": "tema", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": (10, 50)}},
    {"name": "trima", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": (10, 50)}},
    {"name": "tsf", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": (10, 50)}},
    {"name": "typprice", "inputs": ["High", "Low", "Close"], "params": {}, "param_grid": {}},
    {"name": "vidya", "inputs": ["Close"], "params": {"short_period": 20, "long_period":50, "alpha": 0.2}, "param_grid": {"short_period": (10, 50), "long_period":(20,50), "alpha": (0.1, 0.3)}},
    {"name": "vwma", "inputs": ["Close", "Volume"], "params": {"period": 20}, "param_grid": {"period": (10, 50)}},
    {"name": "wcprice", "inputs": ["High", "Low", "Close"], "params": {}, "param_grid": {}},
    {"name": "wilders", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": (10, 50)}},
    {"name": "wma", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": (10, 50)}},
    {"name": "zlema", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": (10, 50)}},

    # Indicators
    {"name": "ad", "inputs": ["High", "Low", "Close", "Volume"], "params": {}, "param_grid": {}},
    {"name": "adosc", "inputs": ["High", "Low", "Close", "Volume"], "params": {"short_period": 3, "long_period": 10}, "param_grid": {"short_period": (3, 7), "long_period": (10, 20)}},
    {"name": "adx", "inputs": ["High", "Low", "Close"], "params": {"period": 14}, "param_grid": {"period": (10, 30)}},
    {"name": "adxr", "inputs": ["High", "Low", "Close"], "params": {"period": 14}, "param_grid": {"period": (10, 30)}},
    {"name": "ao", "inputs": ["High", "Low"], "params": {}, "param_grid": {}},
    {"name": "apo", "inputs": ["Close"], "params": {"short_period": 12, "long_period": 26}, "param_grid": {"short_period": (10, 14), "long_period": (24, 30)}},
    {"name": "aroon", "inputs": ["High", "Low"], "params": {"period": 14}, "param_grid": {"period": (10, 25)}},
    {"name": "aroonosc", "inputs": ["High", "Low"], "params": {"period": 14}, "param_grid": {"period": (10, 25)}},
    {"name": "atr", "inputs": ["High", "Low", "Close"], "params": {"period": 14}, "param_grid": {"period": (10, 30)}},
    {"name": "bop", "inputs": ["Open", "High", "Low", "Close"], "params": {}, "param_grid": {}},
    {"name": "cci", "inputs": ["High", "Low", "Close"], "params": {"period": 20}, "param_grid": {"period": (14, 50)}},
    {"name": "cmo", "inputs": ["Close"], "params": {"period": 14}, "param_grid": {"period": (10, 30)}},
    {"name": "cvi", "inputs": ["High", "Low"], "params": {"period": 14}, "param_grid": {"period": (10, 30)}},
    {"name": "di", "inputs": ["High", "Low", "Close"], "params": {"period": 14}, "param_grid": {"period": (10, 30)}},
    {"name": "dm", "inputs": ["High", "Low"], "params": {"period": 14}, "param_grid": {"period": (10, 30)}},
    {"name": "dpo", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": (14, 50)}},
    {"name": "dx", "inputs": ["High", "Low", "Close"], "params": {"period": 14}, "param_grid": {"period": (10, 30)}},
    {"name": "emv", "inputs": ["High", "Low", "Volume"], "params": {}, "param_grid": {}},
    {"name": "fisher", "inputs": ["High", "Low"], "params": {"period": 10}, "param_grid": {"period": (5, 20)}},
    {"name": "fosc", "inputs": ["Close"], "params": {"period": 10}, "param_grid": {"period": (5, 20)}},
    {"name": "kvo", "inputs": ["High", "Low", "Close", "Volume"], "params": {"short_period": 34, "long_period": 55}, "param_grid": {"short_period": (30, 40), "long_period": (50, 60)}},
    {"name": "linregintercept", "inputs": ["Close"], "params": {"period": 14}, "param_grid": {"period": (10, 30)}},
    {"name": "linregslope", "inputs": ["Close"], "params": {"period": 14}, "param_grid": {"period": (10, 30)}},
    {
        "name": "macd",
        "inputs": ["Close"],
        "params": {"short_period": 12, "long_period": 26, "signal_period": 9},
        "param_grid": {"short_period": (10, 14), "long_period": (24, 30), "signal_period": (7, 12)}
    },
    {"name": "marketfi", "inputs": ["High", "Low", "Volume"], "params": {}, "param_grid": {}},
    {"name": "mass", "inputs": ["High", "Low"], "params": {"period": 9}, "param_grid": {"period": (7, 15)}},
    {"name": "mfi", "inputs": ["High", "Low", "Close", "Volume"], "params": {"period": 14}, "param_grid": {"period": (10, 30)}},
    {"name": "minidmi", "inputs": ["High", "Low", "Close"], "params": {"period": 14}, "param_grid": {"period": (10, 30)}},
    {"name": "minus_di", "inputs": ["High", "Low", "Close"], "params": {"period": 14}, "param_grid": {"period": (10, 30)}},
    {"name": "minus_dm", "inputs": ["High", "Low"], "params": {"period": 14}, "param_grid": {"period": (10, 30)}},
    {"name": "mom", "inputs": ["Close"], "params": {"period": 10}, "param_grid": {"period": (7, 15)}},
    {"name": "msw", "inputs": ["Close"], "params": {"period": 14}, "param_grid": {"period": (10, 30)}},
    {"name": "natr", "inputs": ["High", "Low", "Close"], "params": {"period": 14}, "param_grid": {"period": (10, 30)}},
    {"name": "nvi", "inputs": ['Close', 'Volume'], "params": {}, "param_grid": {}},
    {"name": "obv", "inputs": ["Close", "Volume"], "params": {}, "param_grid": {}},
    {"name": "plus_di", "inputs": ["High", "Low", "Close"], "params": {"period": 14}, "param_grid": {"period": (10, 30)}},
    {"name": "plus_dm", "inputs": ["High", "Low"], "params": {"period": 14}, "param_grid": {"period": (10, 30)}},
    {"name": "ppo", "inputs": ["Close"], "params": {"short_period": 12, "long_period": 26}, "param_grid": {"short_period": (10, 14), "long_period": (24, 30)}},
    {"name": "pvi", "inputs": ["Close", "Volume"], "params": {}, "param_grid": {}},
    {"name": "roc", "inputs": ["Close"], "params": {"period": 10}, "param_grid": {"period": (7, 15)}},
    {"name": "rocp", "inputs": ["Close"], "params": {"period": 10}, "param_grid": {"period": (7, 15)}},
    {"name": "rocr", "inputs": ["Close"], "params": {"period": 10}, "param_grid": {"period": (7, 15)}},
    {"name": "rocr100", "inputs": ["Close"], "params": {"period": 10}, "param_grid": {"period": (7, 15)}},
    {"name": "rsi", "inputs": ["Close"], "params": {"period": 14}, "param_grid": {"period": (10, 30)}},
    {"name": "sar", "inputs": ["High", "Low"], "params": {"start": 0.02, "increment": 0.02, "max": 0.2}, "param_grid": {"start": (0.01, 0.03), "increment": (0.01, 0.03), "max": (0.1, 0.3)}},
    {"name": "sma", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": (10, 50)}},
    {"name": "stoch", "inputs": ["High", "Low", "Close"], "params": {"pct_k_period": 5, "pct_k_slowing_period": 3, "pct_d_period": 3}, "param_grid": {"pct_k_period": (3, 7), "pct_k_slowing_period": (2, 5), "pct_d_period": (2, 5)}},
    {"name": "stochrsi", "inputs": ["Close"], "params": {"period": 14}, "param_grid": {"period": (10, 30)}},
    {"name": "sub", "inputs": ["Close", "Close"], "params": {}, "param_grid": {}},
    {"name": "sum", "inputs": ["Close"], "params": {"period": 14}, "param_grid": {"period": (10, 30)}},
    {"name": "trange", "inputs": ["High", "Low", "Close"], "params": {}, "param_grid": {}},
    {"name": "trima", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": (10, 50)}},
    {"name": "trix", "inputs": ["Close"], "params": {"period": 15}, "param_grid": {"period": (10, 30)}},
    {"name": "tsf", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": (10, 50)}},
    {"name": "typprice", "inputs": ["High", "Low", "Close"], "params": {}, "param_grid": {}},
    {"name": "ultosc", "inputs": ["High", "Low", "Close"], "params": {"short_period": 7, "medium_period": 14, "long_period": 28}, "param_grid": {"short_period": (5, 10), "medium_period": (10, 20), "long_period": (20, 40)}},
    {"name": "var", "inputs": ["Close"], "params": {"period": 14, "nbdev": 1}, "param_grid": {"period": (10, 30), "nbdev": (0.5, 2)}},
    {"name": "vhf", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": (10, 50)}},
    {"name": "vwma", "inputs": ["Close", "Volume"], "params": {"period": 20}, "param_grid": {"period": (10, 50)}},
    {"name": "vosc", "inputs": ["Volume"], "params": {"short_period": 7, "long_period": 28}, "param_grid": {"short_period": (5, 10), "long_period": (20, 40)}},
    {"name": "wclprice", "inputs": ["High", "Low", "Close"], "params": {}, "param_grid": {}},
    {"name": "wad", "inputs": ["High", "Low", "Close"], "params": {}, "param_grid": {}},
    {"name": "wilders", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": (10, 50)}},
    {"name": "willr", "inputs": ["High", "Low", "Close"], "params": {"period": 14}, "param_grid": {"period": (10, 30)}},
    {"name": "wma", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": (10, 50)}},
    {"name": "zlema", "inputs": ["Close"], "params": {"period": 20}, "param_grid": {"period": (10, 50)}},
]
